$quest_list << Quest.new("New Quest", 0, 0, "Detail Of The New Quest")
$quest_list[0].update_page(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update_page(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")
$quest_list[0].update(0, "Update Detail")